### ISSUE TITLE
Keyboard not detected on XHCI controller on some ports

### ISSUE THREAD

**Issue by x86fr** [memtest86plus/memtest86plus#31] opened 2022-04-01 19:30 UTC
I've received a lot of reports from beta-tester with keyboards not detected on modern motherboards (Ryzen 3000 -> 5000 & Intel 9th gen to 13th gen).

I tried to isolate a "reference" system with the issue to grab all the information needed. 

The motherboard is a Asus TUF B550 PLUS.

![image](https://user-images.githubusercontent.com/38105886/161327429-1748a7aa-8660-4035-add6-cbd28f38aa75.png)

On the front panel, a keyboard plugged on ports 1 & 2 works fine, but a keyboard plugged on ports 3 & 4 is not detected.

Here is the log displayed by Memtest86+ for every port group :

**Port 1 (USB 3.2 Gen 2) -> OK**
```
Scanning for USB keyboards...
Found XHCI controller 1022:43ee at fcfa0000 size 00008000
 Found 0 devices, 0 keyboards
Found XHCI controller 1022:1639 at fcb00000 size 00100000
 Found 0 devices, 0 keyboards
Found XHCI controller 1022:1639 at fcb00000 size 00100000
 Keyboard found on port 1 interface 0 endpoint 1
 Found 1 device, 1 keyboard
Press any key to continue...
```

**Port 2 (USB 3.2 Gen 1) -> OK**
```
Scanning for USB keyboards...
Found XHCI controller 1022:43ee at fcfa0000 size 00008000
 Found 0 devices, 0 keyboards
Found XHCI controller 1022:1639 at fcb00000 size 00100000
 Keyboard found on port 1 interface 0 endpoint 1
 Found 1 device, 1 keyboard
Found XHCI controller 1022:1639 at fcb00000 size 00100000
 Found 0 devices, 0 keyboards
Press any key to continue...
```

**Port 3 (USB 2.0) -> FAIL
Port 4 (USB 3.2 Gen 1) -> FAIL**
```
Scanning for USB keyboards...
Found XHCI controller 1022:43ee at fcfa0000 size 00008000
 Found 0 devices, 0 keyboards
Found XHCI controller 1022:1639 at fcb00000 size 00100000
 Found 0 devices, 0 keyboards
Found XHCI controller 1022:1639 at fcb00000 size 00100000
 Found 0 devices, 0 keyboards
Press any key to continue...
```

USB controllers detection seems OK. 

Here are some logs (reduced to only show USB-related data) with the **keyboard plugged on Port 3** (not detected by Memtest86+)

PCI devices
```
   Seg  Bus  Dev  Func
   ---  ---  ---  ----
    00   01   00    00 ==> Serial Bus Controllers - USB
             Vendor 1022 Device 43EE Prog Interface 30
    00   06   00    03 ==> Serial Bus Controllers - USB
             Vendor 1022 Device 1639 Prog Interface 30
    00   06   00    04 ==> Serial Bus Controllers - USB
             Vendor 1022 Device 1639 Prog Interface 30
```

Devtree:

```
 Ctrl[105] PciRoot(0x0)
   Ctrl[1C0] AMI USB Host Controller(XHCI)
     Ctrl[1EA] AURA LED Controller
     Ctrl[1EB] AURA LED Controller
     Ctrl[1EC] ASM107x
     Ctrl[1ED] HP USB Multimedia Keyboard
       Ctrl[18B] AMI Console Splitter
     Ctrl[1EE] HP USB Multimedia Keyboard
   Ctrl[1CE] AMI USB Host Controller(XHCI)
   Ctrl[1CF] AMI USB Host Controller(XHCI)
     Ctrl[1EF] 䃒챘�䖞騴Ⴧ뻫瑰污
       Ctrl[1F0] FAT File System
```
Devices :

```
     T   D
     Y C I
     P F A
CTRL E G G #P #D #C  Device Name
==== = = = == == === =========================================================
 105 R - -  0  1  30 PciRoot(0x0)
 18B D - -  2  1   0 AMI Console Splitter
 1BB D - -  1  0   0 PciRoot(0x0)/Pci(0x0,0x0)
 1C0 B - -  1  2   5 AMI USB Host Controller(XHCI)
 1C1 D - -  1  2   0 AHCI Mass Storage Controller
 1C2 D - -  1  0   0 PciRoot(0x0)/Pci(0x2,0x1)/Pci(0x0,0x2)
 1CD D - -  1  0   0 PciRoot(0x0)/Pci(0x8,0x1)/Pci(0x0,0x2)
 1CE D - -  1  2   0 AMI USB Host Controller(XHCI)
 1CF B - -  1  2   1 AMI USB Host Controller(XHCI)
 1D0 D - -  1  0   0 PciRoot(0x0)/Pci(0x8,0x1)/Pci(0x0,0x6)
 1E9 B - -  1  3   1 DFP1_DP
 1EA D - -  1  0   0 AURA LED Controller
 1EB D - -  1  0   0 AURA LED Controller
 1EC D - -  1  0   0 ASM107x
 1ED B - -  1  2   1 HP USB Multimedia Keyboard
 1EE D - -  1  1   0 HP USB Multimedia Keyboard
 1EF B - -  1  3   1 䃒챘�䖞騴Ⴧ뻫瑰污
 1F0 D - -  1  2   0 FAT File System
 1F2 B - -  1  3   4 Realtek PCIe 2.5GBE Family Controller
```

The USB ports that don't work are on the external 1022:43ee XHCI controller located on the south-bridge chip (AMD 500-Series "Promontory" Chipset). The USB ports that do work  are on the internal 1022:1639 XHCI controller (located on the SoC itself).

Will try to debug but any idea very welcome :)

**Comment by x86fr** [comment] 2022-04-01 20:08
Ok, that was faster than expected. 😀

Just a typo on the XHCI reset code. With delay back at 100ms, everything's working as expected.

**Port 3 (USB 2.0) -> OK
Port 4 (USB 3.2 Gen 1) -> OK** 

```
Scanning for USB keyboards...
Found XHCI controller 1022:43ee at fcfa0000 size 00008000
 4  port hub found on port 11
 Keyboard found on port 13 interface 0 endpoint 1
Found 3 devices, 1 keyboard
Found XHCI controller 1022:1639 at fcb00000 size 00100000
 Found 0 devices, 0 keyboards
Found XHCI controller 1022:1639 at fcb00000 size 00100000
 Found 0 devices, 0 keyboards
Press any key to continue...
```

**Comment by martinwhitaker** [comment] 2022-04-01 21:28
That wasn't a typo. The USB 2.0 spec. states the maximum reset recovery time is 10ms.

**Comment by x86fr** [comment] 2022-04-01 21:45
As it's an USB 3.1 controller, maybe the reset is longer. I've tried with 50 ms and it still don't work. 100 ms seems to be the minimum.

**Comment by x86fr** [comment] 2022-04-01 22:31
Seems there is many discussions about TRSTRCY delay online. 

You're right, the specs is 10 ms but it seems that a lot of USB devices requires a MUCH longer delay. Even the Linux usb drivers increases it to 50 ms at least, and even 150 ms (!) when a hub is detected.

https://github.com/torvalds/linux/blob/master/drivers/usb/core/hub.c
Line 3043+

```
	/* TRSTRCY = 10 ms; plus some extra */
	reset_recovery_time = 10 + 40;

	/* Hub needs extra delay after resetting its port. */
	if (hub->hdev->quirks & USB_QUIRK_HUB_SLOW_RESET)
		reset_recovery_time += 100;

	msleep(reset_recovery_time);
```

**Comment by martinwhitaker** [comment] 2022-04-01 22:38
That's going to make scanning for keyboards horribly slow.

**Comment by x86fr** [comment] 2022-04-01 22:45
Took about ~1.5/2 seconds on a real-life computer with many USB devices plugged in. Not that bad.  😊

**Comment by martinwhitaker** [comment] 2022-04-01 22:55
I'm suspicious about this. The USB_QUIRK_HUB_SLOW_RESET is only used for one specific USB hub (Terminus Technology Inc. Hub), and the 50ms delay used for other devices didn't work for you. Also the reset recovery time is a property of the USB device - if you were using the same keyboard when testing the other controller, it recovered within 10ms then. I wonder if this controller is clearing the Port Reset bit too soon. Can you time how long `reset_xhci_port()` is taking.

**Comment by martinwhitaker** [comment] 2022-04-01 23:25
OK, I've reproduced this on my Ryzen system, so I can investigate further.

**Comment by martinwhitaker** [comment] 2022-04-01 23:32
And indeed, `reset_xhci_port()` is taking 0ms on that controller and the expected 50ms on the other controllers.

**Comment by x86fr** [comment] 2022-04-01 23:43
5500 cycles (~1.5 µs) on ports 3/4, 
~200k cycles (50 ms) on ports 1/2

**Comment by martinwhitaker** [comment] 2022-04-02 00:18
Try this fix (with the reset recovery time set back to 10ms):
````
--- a/system/xhci.c
+++ b/system/xhci.c
@@ -473,6 +473,9 @@ static int get_xhci_device_speed(xhci_op_regs_t *op_regs, int port_idx)
 static bool reset_xhci_port(xhci_op_regs_t *op_regs, int port_idx)
 {
     write32(&op_regs->port_regs[port_idx].sc, XHCI_PORT_SC_PP | XHCI_PORT_SC_PR);
+
+    usleep(1*MILLISEC);  // some controllers don't set the PR bit immediately
+
     return wait_until_clr(&op_regs->port_regs[port_idx].sc, XHCI_PORT_SC_PR, 1000*MILLISEC);
 }
 
````
It works for me.

**Comment by x86fr** [comment] 2022-04-02 00:27
Almost work, but some erratic results on Ryzen (3 ok out of 5 try on the USB 3.1 ports)
Don't work on RPL-S.

But increasing to 3 msec makes it works anytime on both :)

Maybe increase to 5ms for safety?

**Comment by x86fr** [comment] 2022-04-02 00:35
PS: With another keyboard, it works on every try on both platform with just 1 msec 😲

**Comment by x86fr** [comment] 2022-04-02 00:48
Sorry typo on my side! Time to go to sleep.

It starts to work everywhere with usleep(~5), not usleep(5*MILLISEC) !

So 1ms is more than enough :)

**Comment by martinwhitaker** [comment] 2022-04-02 08:37
I've pushed what I think is a better fix for this. Works OK on my Ryzen machine.

I'll wait to see if it's needed before increasing the reset recovery delay beyond the standard 10ms. We could add a command line option for that.

**Comment by x86fr** [comment] 2022-04-02 13:24
Excellent! Seems OK on all platforms with the 10 ms TRSTRCY now. 

Waiting for betatester's feedback before closing.

**Closed** 2022-04-05 23:01 UTC
Labels: bug
