### ISSUE TITLE
Testing 129GB out of 127GB

### ISSUE THREAD

**Issue by Infinoid** [memtest86plus/memtest86plus#194] opened 2022-10-26 13:54 UTC
The test itself seems to behave nicely, I think this is only a cosmetic issue.  Looks like a GB vs GiB mismatch?

![image](https://user-images.githubusercontent.com/50254/198044785-e321f5bd-5455-41cf-ba9f-47696e41cb6a.png)

**Comment by debrouxl** [comment] 2022-10-26 13:58
Duplicate of #192 / #193 , unless there's a convincing reason to believe otherwise :)

**Closed by debrouxl** 2022-10-26 13:58 UTC
