### ISSUE TITLE
Fail Test #9 [Modulo 20, random pattern] on Huananzhi with dual CPU 

### ISSUE THREAD

**Issue by Adler-lug** [memtest86plus/memtest86plus#216] opened 2022-11-26 13:56 UTC
Hi.
On Huananzhi X79-16D with 2x E5-2687W v2 on Test #9  [Modulo 20random pattern] I keep getting FAIL on two motherboards, two sets of processor and memory (8x16Gb 1600). 
On old 5.31b and two different versions from PassMark Memtest86 i have PASS.
Tell me what could be the problem?
![Memtest_FAIL](https://user-images.githubusercontent.com/305086/204092342-3de04048-5c1a-4694-9226-699bd685b2a9.jpg)

**Comment by x86fr** [comment] 2022-11-26 14:07
The betatester team is currently investigating a similar issue on another platform. Can you please check is the memory address are all located in close proximity? Another test with SMT disabled could be interesting.

**Comment by Adler-lug** [comment] 2022-11-26 17:08
I will try on Monday-Tuesday, but I do not promise, because these are working servers that are needed in work

**Comment by Adler-lug** [comment] 2022-11-28 08:15
I checked almost all the memory on this test in sequential mode on one core and the error did not occur.
![memtest](https://user-images.githubusercontent.com/305086/204226993-0ec5d222-8176-41e9-a86e-f59f52717ebc.jpg)

**Comment by vanderspek-a** [comment] 2022-11-30 17:30
I am seeing a failure in test9 using the released V6.0 on a board with the Intel 4310 CPU and C621A chipset and 8x16GiB RDIMMs.  The failure happens on 2 out of 3 vendor's motherboards and with a variety of vendor's DIMMs (always using a matched set of 8 DIMMs)

**Comment by dom-lgtm** [comment] 2022-12-01 13:07
I get the issue on a corsair icue 4000X machine 

![signal-2022-12-01-135908_002](https://user-images.githubusercontent.com/51714033/205060567-ea2f8843-6e22-437b-a819-cb74ff32c308.jpeg)

**Comment by loopforever** [comment] 2022-12-05 17:11
Through repeated trial and error I believe I am having this same issue as the other folks in this thread. I have tried multiple DIMMs in different slots, all throw significant (>=1024) errors at roughly the same addresses on Test 9. 

At first I thought I had bad DIMMs, then I thought I had bad motherboard, now I think there's just a problem with Test 9.

My specs are:
i9-13900k
Kingston Fury 4x32GB (KF548C38BBK2-64) with XMP = Auto (no profile selected)
ASRock Z690M PG Riptide/D5 with 8.02 (latest) BIOS

**Comment by x86fr** [comment] 2022-12-05 18:03
All errors on test 9 are not false errors. This is a very specific case with Dual Socket Motherboards.

If you find errors with any other platforms, there is 99.999% chance they are real errors.

**Comment by Jeff-Smart** [comment] 2022-12-08 17:51
Seems fishy to me that the Memory Test fails only on Multicore, neither Round Robin nor Sequential through the Error. I verified with Passmarks Memtest 10 and the Memory Test of Windows 11, no Errors detected.
Does Memtest use its own memory configuraation for instance by using SPD Settings or does it use the Settings by the UEFI?
I think it is also strange that these errors happen in the same early are of the memory map.
![Screenshot 2022-12-08](https://user-images.githubusercontent.com/46821760/206526711-4b0ef69a-f551-4fc2-a2c3-621591b7a33f.jpg)

**Comment by loopforever** [comment] 2022-12-08 18:19
I just want to add, memtest86+ repeated failed Test 9 with each of the four DIMMS, inserted one at a time in every slot (ie. the DIMMs are not bad, but the motherboard or CPU might be).

Confused and concerned, I actually purchased the Passmark Memtest86 so that I could run a parallel test and I ran it for almost 20 hours with zero errors, including their Modulo 20 - Test 9.

I only posted my prior comment as (at the time) there were at least two people on i9-13900 getting failures on Test 9. And now there are 3 based on @Jeff-Smart's screenshot. I do not think that's a coincidence.

**Comment by vanderspek-a** [comment] 2022-12-08 18:52
The failure I was seeing with the Intel 4314 CPU and C621A chipset and 8x16GiB RDIMMs only happens if I have CSM disabled in my BIOS configuration.  When I enable CSM,  test#9 then runs without error.  That option option enables a "compatibility support module" for supporting legacy BIOS APIs.  See "CSM booting" at https://en.wikipedia.org/wiki/UEFI for an explanation.  I don't know why this should make a difference.  The two vendor's boardsets that failed had CSM disabled and after enabling it the test passed.  The vendor's boardset that passed had CSM enabled.  The latest passmark MemTest86 passes regardless of the CSM setting.

**Comment by Jeff-Smart** [comment] 2022-12-08 19:07
Found someone in another forum with z790+i13900k and also memtest86+ v6 test 9 errors.:

https://www-computerbase-de.translate.goog/forum/threads/memtest86-fail-aber-windows-anscheinend-stabil.2117502/?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp

**Comment by x86fr** [comment] 2022-12-08 19:34
Memtest86+ is used everyday to test at least hundreds and probably thousands of PCs based on 700-series + 13th gen CPU, without any issue related to test 9 or any other test.

A Memtest86+ bug is always possible, but it will be easy to reproduce with the exact same setup (same motherboard, same BIOS rev & settings and same CPU and memory module). I have access to barely any motherboard and any module on the market, so I can test any combination available.

A failure in Memtest86+ while other memory testing tool like Passmark's tool is technically possible. To my knowledge, Memtest86+ is the only memory testing tool able to test the **entire memory** available for an operating system. Eg: Testmem5 is a Windows application and can't access memory reserved by Windows (that's a LOT of memory). Passmark's tool is an UEFI application and can't access the memory used by the UEFI framework.

If there is an issue on the memory range used by Windows or by the UEFI Passmark, Memtest86+ will found it, but Passmark or Testmem5 will report everything's OK.

That doesn't mean you will see memory issue in a real-life scenario, as a failure on such a reserved memory range can stay unused forever.

> The failure I was seeing with the Intel 4314 CPU and C621A chipset and 8x16GiB RDIMMs only happens if I have CSM disabled in my BIOS configuration. When I enable CSM, test#9 then runs without error. That option option enables a "compatibility support module" for supporting legacy BIOS APIs. See "CSM booting" at https://en.wikipedia.org/wiki/UEFI for an explanation. I don't know why this should make a difference. The two vendor's boardsets that failed had CSM disabled and after enabling it the test passed. The vendor's boardset that passed had CSM enabled. The latest passmark MemTest86 passes regardless of the CSM setting.

This makes sense. If the issue is located somewhere in the memory range used by the UEFI framework, it will vanish when using CSM (as the UEFI framework is not loaded). In that specific case, the issue is probably a BIOS bug, marking part of the memory used by the UEFI framework as free and usable for software, while this memory area actually used and should be marked as reserved.

**Comment by vanderspek-a** [comment] 2022-12-08 19:46
Thanks x86fr - Your explanation makes sense.  We are switching our config to have CSM on to avoid the issue.  Our board manufacturer is digging deeper into this and I'll pass your analysis along to them.  If they come up with a fix on their side, I'll request they update this thread with what they found.  NDAs prevent me from doing so.

**Comment by martinwhitaker** [comment] 2022-12-08 19:49
One thing to investigate is whether test 9 is robust when given a very small memory segment (say one 4K page) and many CPU threads. I always meant to look into that (being somewhat suspicious of it), but too many other things intervened.

**Comment by Jeff-Smart** [comment] 2022-12-09 03:07
> Memtest86+ is used everyday to test at least hundreds and probably thousands of PCs based on 700-series + 13th gen CPU, without any issue related to test 9 or any other test.

What shall this tell us? That memtest86+ V6 is impeccable? I do not think so. Please explain circumstances under which parallel mode throws errors while sequential and round robin do not.
 
> A Memtest86+ bug is always possible, but it will be easy to reproduce with the exact same setup (same motherboard, same BIOS rev & settings and same CPU and memory module). I have access to barely any motherboard and any module on the market, so I can test any combination available.

You did not ask for this information.
 
> A failure in Memtest86+ while other memory testing tool like Passmark's tool is technically possible. To my knowledge, Memtest86+ is the only memory testing tool able to test the **entire memory** available for an operating system. Eg: Testmem5 is a Windows application and can't access memory reserved by Windows (that's a LOT of memory). Passmark's tool is an UEFI application and can't access the memory used by the UEFI framework.

Testing entire (DDR 5) memory would need memtest to run from outside that memory, i do not consider that the case and your statement therefore overblown. Please state the memory footprint of memtest86+ v6.

I looked at the filesizes and the documentation of passmarks memtest: they are a  << 10MB,  the interface and MT support rely on the UEFI and passmark recommends to switch to single thread in case of problems, suggesting that its results are as reliable as the MT results.

I see errors in many screenshots of failed test 9 below 1GB, that is probably not by chance.
 
> If there is an issue on the memory range used by Windows or by the UEFI Passmark, Memtest86+ will found it, but Passmark or Testmem5 will report everything's OK.

Most of the errors reported for the tested system happen consecutive at offset around 750MB, so there ist plenty of space for passmarks memtest. As i said, running sequential and round robin do not throw an error in memtest86+ v6 test 9, explain.

In case the column pCPU stands for (p)erformance it does not make sense, if it is threads  it is supposed to only use 16 threads so why is it counting running threads up to 30 in the image?

> This makes sense. If the issue is located somewhere in the memory range used by the UEFI framework, it will vanish when using CSM (as the UEFI framework is not loaded). In that specific case, the issue is probably a BIOS bug, marking part of the memory used by the UEFI framework as free and usable for software, while this memory area actually used and should be marked as reserved.

I do not think that enabling CSM does anything to the lessen the memory footprint of the uefi, instead it will probably increase the memory footprint because of the usage of option roms and therefore aggravate the memory problem.

**Comment by debrouxl** [comment] 2022-12-09 08:39
> Testing entire (DDR 5) memory would need memtest to run from outside that memory, i do not consider that the case and your statement therefore overblown. Please state the memory footprint of memtest86+ v6.

* the binary + BSS are a bit over 400 KBs on x86_64 for 256 execution units support, according to `size` on built intermediate binaries, whereas the raw binary (not counting BSS) of the crippled version of PassMark's proprietary memory tester available for public download at no fee, a.k.a "Free Edition" with support for 16 execution units, was over 1 MB at some point in the 9.x series, last time I downloaded that thing, before woarking on memtest86+.
* however, memtest86+ goes to the length of relocating itself throughout its execution, which includes relocating pointers inside nearly all internal data structures, eliminating this already low memory footprint.

As you can see, Sam mentioned "**entire memory** available for an operating system". I'll use different emphasis here: "entire memory **available for an operating system**". Indeed, memtest86+ does not attempt to read and write improper data into I/O space or MMIO for, say, USB controllers - and neither do other memory testers or general-purpose OS kernels :)
A memory page or so is reserved for internal SMP handling, but I'd have to check if this isn't getting relocated either.

> I looked at the filesizes and the documentation of passmarks memtest: they are a << 10MB, the interface and MT support rely on the UEFI and passmark recommends to switch to single thread in case of problems, suggesting that its results are as reliable as the MT results.

> I do not think that enabling CSM does anything to the lessen the memory footprint of the uefi, instead it will probably increase the memory footprint because of the usage of option roms and therefore aggravate the memory problem.

The weight of PassMark's memory tester is one thing; the memory areas permanently reserved by the computer's UEFI firmware are another. According to comments in other issues or discussions in this repo, said firmware can reserve hundreds of megabytes on some platforms - when it is running in UEFI mode, that is; no such large reservations are made when running in CSM.

> In case the column pCPU stands for (p)erformance it does not make sense, if it is threads it is supposed to only use 16 threads so why is it counting running threads up to 30 in the image?
It stands for "physical CPU", as only a small number of recent processor series have that distinction between performance and efficiency cores. the physical CPU numbers depend on the platform and AFAIK the BIOS configuration (MADT / APIC table).

**Comment by martinwhitaker** [comment] 2022-12-09 08:57
@Jeff-Smart, please, less of the aggressive tone. Memtest86+ is free and open source software, created by volunteers in their spare time. You have the source code and can reproduce the problem. Please find and fix the bug for us.

**Comment by Jeff-Smart** [comment] 2022-12-09 16:29
> @Jeff-Smart, please, less of the aggressive tone. Memtest86+ is free and open source software, created by volunteers in their spare time. You have the source code and can reproduce the problem. Please find and fix the bug for us.

I am sorry if i hurt your feelings .-> but if discourse is not possible i am out.
I looked into the code and think that i would probably be faster writing a memtest from scratch than thoroughly understanding memtest86+ v6 so i can not help here.

One last thing, i am grateful that free tools like memtest86+ v6 exist but you overlook one important thing: you have a responsibility for the consequences of releasing any tool to the public, free or not! People rely on such tools and if they indicate problems they will invest their time and money because of these indications. Maybe they even get in legal quarrels because of these indications.

**Comment by 01e3** [comment] 2022-12-09 17:38
@Jeff-Smart  it is good to see your passion and motivation, but a friendly warning that you are very quickly crossing a line here of being a jerk.

I would strongly recommend you to re-consider your communication style, this is not how you can get devs attention and help.

"_I am sorry if i hurt your feelings_" is not only a classic [Non-apology apology](https://en.wikipedia.org/wiki/Non-apology_apology), but is also very rude.

Regarding "_It would probably be faster writing a memtest from scratch than thoroughly understanding memtest86+_", it not only sounds disrespectful, arrogant and naive but is simply wrong. It is not that hard to understand the code and to be able to contribution, and definitely much easier than writing anything close to what it provides currently. The project members are also easy and friendly to work with, perhaps long as you don't insult them.

**Comment by martinwhitaker** [comment] 2022-12-10 15:43
As per my earlier comment, my suspicion proved well founded - both the Modulo-20 and the Block Move tests could fail when given very small memory segments with a large  number of active CPUs. I have pushed a fix for that to the main branch. Please test whether it fixes this issue. If you don't want to build from source, the fix should be present in the next nightly build.

**Comment by Jeff-Smart** [comment] 2022-12-11 02:30
![20221211_031419](https://user-images.githubusercontent.com/46821760/206883414-853415fe-ce15-4bad-99e7-37212c54cf85.jpg)

Out of completeness i rerun the patched Version, as one can see it passes now, i hope the patch does not skip small segments.

Your build system is broken, the nightly build at this time contains binaries with date:
![grafik](https://user-images.githubusercontent.com/46821760/206883563-8124a4ab-0a6b-428f-a74d-a780507e9f29.png)
MD5:596bf1117881b9a2d491cf8279554536 memtest64.efi

I had to build them myself.

**Comment by x86fr** [comment] 2022-12-11 13:42
@vanderspek-a @Adler-lug @loopforever Can you please try the latest nightly build and report if it solves your issue?

We planned a crash test on ASRock Z690M PG Riptide/D5 with the same hardware configuration reported at https://github.com/memtest86plus/memtest86plus/issues/216#issuecomment-1337758792 this week. Unfortunately, we can't run the non-regression tests on this new platform and must stay on our previous ones, but we will check if we can reproduce the issue with this same hardware.

**Comment by loopforever** [comment] 2022-12-11 14:56
Thank you so much. I will try to test this build in a few days (machine is in use and cannot be rebooted right now)... maybe Wednesday this week. I made a small voltage change in the BIOS which I will revert to default to repeat the original test and report back.

**Comment by vanderspek-a** [comment] 2022-12-11 17:19
I downloaded the nightly build this morning and the confirmed failing configuration now passes.  Thank your martinwhitaker!
![image](https://user-images.githubusercontent.com/119525379/206918538-febfb766-859a-48fe-8692-f57f856fb468.png)

**Comment by Adler-lug** [comment] 2022-12-11 17:22
[x86fr](https://github.com/x86fr), the server is in operation and there is no way to check

**Comment by Grocel** [comment] 2022-12-14 20:19
@Jeff-Smart
> i hope the patch does not skip small segments.

Well according to [commit 5a2bc4c960b4a15865a5d6823cf932b4d40df9a6 
](https://github.com/memtest86plus/memtest86plus/commit/5a2bc4c960b4a15865a5d6823cf932b4d40df9a6#comments) it does. But that shouldn't be much of a problem, is it?

**Comment by x86fr** [comment] 2022-12-15 17:59
After hours of trying, I wasn't able to reproduce the issue with the original code and the exact same hardware described in https://github.com/memtest86plus/memtest86plus/issues/216#issuecomment-1337758792

Betatesters never encountered the issue so far, but they'll try many different hardware combination in the next 2 weeks (productions lines are very busy right now due to Xmas). 

There's probably no need to rush the v6.01 release with commit 5a2bc4c right now. 

I'm on a business trip next week, but I'll get all feedbacks in ~10 days, including v6.01 evaluation and non-regression tests. If all goes well, v6.01 will be released around 29/30 Dec.

**Comment by loopforever** [comment] 2022-12-15 18:21
I am sorry for the delay -- the machine has been in use. However, I just reflashed 6.00 (production) onto a USB stick and ran the test:
![PXL_20221215_181402339](https://user-images.githubusercontent.com/68266/207937394-183ecef5-1ebd-4096-8a43-b33bf7c32171.jpg)

And then I re-flashed the USB with the latest nightly build:
![PXL_20221215_181729308](https://user-images.githubusercontent.com/68266/207937449-b01ca7d5-441a-483e-a8a1-d5c0ff23ccfe.jpg)

The test is still running -- but so far 0 errors with the nightly build, whereas the production build throws 1024 errors almost immediately.

I believe @martinwhitaker has fixed my particular issue.

Thank you everyone who has taking this issue into consideration.

**Comment by x86fr** [comment] 2022-12-15 22:37
Can you explain how you created the USB Flash Drive? Do you use UEFI or CSM?

**Comment by loopforever** [comment] 2022-12-16 13:33
> Can you explain how you created the USB Flash Drive? Do you use UEFI or CSM?

In both cases the USB drive was created with the Windows USB installer. CSM is disabled.

**Comment by MatPoliquin** [comment] 2022-12-16 22:42
I have a Huananzhi x88-T8D with dual Xeon 2666v3 and also have errors on Test 9.
Moreover on test 6 (moving blocks) the screen becomes white (and you can see the white pixels appearing from top to bottom as if the vram was overwritten) and the system freezes

**Comment by x86fr** [comment] 2022-12-30 15:37
v6.01 will be released today. To summarize, betatesters were not able to reproduce the issue on production platform, but they didn't find any regressions, so that seems fine.

**Comment by vanderspek-a** [comment] 2022-12-30 16:18
I'll be able to test 6.01 next week on a system that re-produces the failure on earlier releases.

**Comment by vanderspek-a** [comment] 2023-01-04 13:04
I confirmed that test9 fails on 6.00 and passes on 6.01 on this system:
![image](https://user-images.githubusercontent.com/119525379/210561149-7f517e9c-6e05-4edc-8b6e-6a6d00c66829.png)

**Comment by martinwhitaker** [comment] 2023-01-04 13:18
Thanks for the confirmation. Closing as fixed.

**Closed by martinwhitaker** 2023-01-04 13:18 UTC
Labels: bug
