### ISSUE TITLE
USB keyboard behind a USB hub not functional, efi mode

### ISSUE THREAD

**Issue by franck-888** [memtest86plus/memtest86plus#135] opened 2022-07-28 14:49 UTC
6.00b3 + git up to 8a3cac8133430b93129341c3c6105b7f1d3a5445

When booting in efi mode via grub on /boot/memtest86+x64git.efi:
USB keyboard (& wired mouse) attached to a USB hub:
• keyboard works in grub but without boot option does not work in memtest
• keyboard works in grub & with 'keyboard=legacy' works in memtest
USB keyboard attached to computer (at same place):
• keyboard works in grub & without boot option works in memtest

USB hub is RAIDSONIC IB-HUB1402 = https://icybox.de/en/product.php?id=324
UEFI BIOS has 'Legacy USB support' Disabled

motherboard: Gigabyte Technology Co., Ltd. H170-HD3, BIOS F22e 03/09/2018
Skylake Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
![skylake](https://user-images.githubusercontent.com/107723864/181564923-90c4aedd-885f-4011-be84-329c9454984c.jpg)

Linux logs with USB keyboard (& wired mouse) attached to USB hub:
[lsusb.txt](https://github.com/memtest86plus/memtest86plus/files/9211491/lsusb.txt)
[lsusb-t.txt](https://github.com/memtest86plus/memtest86plus/files/9211493/lsusb-t.txt)
[lsusb-v.txt](https://github.com/memtest86plus/memtest86plus/files/9211494/lsusb-v.txt)

[lspci.txt](https://github.com/memtest86plus/memtest86plus/files/9211496/lspci.txt)
[dmesg-t.txt](https://github.com/memtest86plus/memtest86plus/files/9211501/dmesg-t.txt)

Kind regards,
Franck

**Comment by martinwhitaker** [comment] 2022-07-31 19:43
Please attach a screenshot of the USB probe results. You can use the `usbdebug` option to make Memtest86+ pause at the end of the USB probe.

Does adding the `usbinit=2` option make any difference?

**Comment by xrysf03** [comment] 2022-08-02 08:18
Hello everybody, and thanks for the marvellous piece of software that is Memtest86+. The 6.00 beta3 works for me just fine, during the first few occasions. The memory test runs like a cheetah.

I'd like to second @franck-888 in this bug report, I've come to the same problem description: USB keyboard doesn't work for me through an additional USB hub. In my case, the hub chip is on motherboard. The machine is an "industrial panel PC", with a passive-cooled Apollo Lake ATOM. The ATOM SoC's tend to be starved of USB ports, therefore the IPC vendors often integrate an extra hub chip on the mobo. For the record, the original description from my colleagues was "the keyboard only works in those blue USB3 ports" - which means to me that it only works on the USB 2.0 ports that are wired to the legacy pins in the USB3 sockets = these USB 2.0 signals are likely coming straight from the ATOM SoC. Confirmed by lsusb -t.

In my case, Memtest86+ 6.00b3 is booting via PXE in UEFI mode, using ipxe. 
I've discovered the options usbdebug and usbinit=2 or usbinit=3 on my own. The usbinit=2 (or 3) has no positive effect.
I'm attaching screenshots of the "usbdebug" startup screen and some dumps of lsusb and lspci.

Keyboard attached to an auxiliary hub chip, keyboard defunct:
![debug_through-hub](https://user-images.githubusercontent.com/32801920/182323602-14fc13ba-af48-4048-a853-9231d125d8d7.jpg)

Keyboard attached directly to the HCI's on-chip hub (root hub?), keyboard works:
![debug_direct-no-hub](https://user-images.githubusercontent.com/32801920/182323613-14c1f13f-7ae6-49d9-9174-34058ccc01ae.jpg)

[lspci-v.txt](https://github.com/memtest86plus/memtest86plus/files/9240197/lspci-v.txt)
[lspci-vn.txt](https://github.com/memtest86plus/memtest86plus/files/9240198/lspci-vn.txt)
[lsusb-v.txt](https://github.com/memtest86plus/memtest86plus/files/9240200/lsusb-v.txt)
[lsusb-vt_keyb-direct-no-hub.txt](https://github.com/memtest86plus/memtest86plus/files/9240201/lsusb-vt_keyb-direct-no-hub.txt)
[lsusb-vt_usb-keyb-through-extra-hub.txt](https://github.com/memtest86plus/memtest86plus/files/9240202/lsusb-vt_usb-keyb-through-extra-hub.txt)

**Comment by franck-888** [comment] 2022-08-03 15:49
Hi Martin,

Using 6.00b3 + git up to 8a3cac8133430b93129341c3c6105b7f1d3a5445
&
USB keyboard (& USB wired mouse) attached to an external USB hub
When booting in efi mode via grub on /boot/memtest86+x64git.efi:
• with option 'usbdebug': keyboard works in grub but does not work in memtest. Memtest detects no keyboard.
• with option 'usbdebug usbinit=2': same
• with option 'usbdebug usbinit=3': same

Above 3 cases displayed exactly same message, so I just post 1 image:
![pic](https://user-images.githubusercontent.com/107723864/182652006-0cc26ce1-b42e-470f-a2c5-30a4c00db9e9.jpg)

Are you able to reproduce this behavior on your side too ?
As xrysf03 & me encountered it, it seems not to be config specific.

Thx, Franck

**Comment by martinwhitaker** [comment] 2022-08-05 16:26
OK, I've managed to reproduce it, but only on an Intel system using an XHCI controller. On the same system but using an EHCI controller, or on an AMD system using an XHCI controller (all with the same hub and keyboard) the keyboard is detected and working.

**Comment by franck-888** [comment] 2022-08-05 18:04
Thanks for your feedback. That will surely ease the bug fixing.

**Comment by martinwhitaker** [comment] 2022-08-05 19:56
This should be fixed by commit 1316c6c. Please test if it works for you.

**Comment by franck-888** [comment] 2022-08-05 19:58
Thx, I should be able to test it next week. I will let you know the result.

**Comment by cwsystem76** [comment] 2022-08-06 17:51
This _appears_ to be the same problem I was having with a pair of keyboards with integrated USB hubs (as described here: https://github.com/memtest86plus/memtest86plus/discussions/45#discussioncomment-2585958), a System76 Launch keyboard and a Dell SK-8135, combined with an Intel Z87-based motherboard. Things have been busy and I didn't have a chance to run more tests and write up a new issue for that problem, but I have a little time this weekend to contribute to this existing issue.

I've done a build from current source, and the fix in commit https://github.com/memtest86plus/memtest86plus/commit/1316c6c099a988b2e20a2e2e48e04784281008d1 appears to have resolved the problem for the Launch (which has a USB-C+USB-3 hub in it) but not the Dell (which has a USB-1 hub). This is when booting from a USB stick written with the output from `make iso`; I don't have the time at the moment to do more extensive testing with the GRUB ISO version and the various USB parameters, but if it would help I can try to find the time later. The Launch works when connected to either the USB-2 or USB-3 ports; the Dell works with neither.

**Comment by franck-888** [comment] 2022-08-08 04:28
Hi Martin,

Using 6.00b3 + git up to 148dfd4d540cef3dd216fef74439e90c69d3c752
&
USB keyboard (& USB wired mouse) attached to an external USB hub
When booting in efi mode via grub on /boot/memtest86+x64git.efi:
Keyboard works in memtest: Memtest detects keyboard in all cases:
• without any option
• with option 'usbdebug'
• with option 'usbdebug usbinit=2'
• with option 'usbdebug usbinit=3'

=> from my side bug is solved. Thanks for your patch.

I hope @xrysf03 & @cwsystem76 will be positive too.

Kind regards,
Franck

**Comment by cwsystem76** [comment] 2022-08-11 14:39
If @franck-888 's and @xrysf03 's keyboards and hubs are working, feel free to close out this issue. I'll need to do more testing with the Dell keyboard and that may take a bit (things are very busy right now), and there's no need to hold this issue open while I do that.

**Comment by martinwhitaker** [comment] 2022-08-11 15:18
@xrysf03 , please test the latest nightly build to see if this is fixed for you.

@cwsystem76 , as the latest code fixes the problem with the System76 keyboard, it seems probable that the problem with the Dell keyboard has a different cause, so please do open a new issue for that. I don't own a USB-1 hub, so can't attempt to reproduce it.

**Comment by martinwhitaker** [comment] 2022-08-20 09:23
No response from @xrysf03 , so closing as fixed.

**Closed by martinwhitaker** 2022-08-20 09:23 UTC
Labels: bug
