### ISSUE TITLE
DDR5 Bank switch issue on ASUS Motherboards

### ISSUE THREAD

**Issue by rocketraman** [memtest86plus/memtest86plus#110] opened 2022-06-27 06:17 UTC
32 GB DIMM show as 2 GB in the per-slot memory size, though the total memory size detected is fine. The exact output looks like this:

![PXL_20220627_061405568](https://user-images.githubusercontent.com/53049/175871805-c9df67d7-2977-4d02-b22a-aa20fae83a42.jpg)

Using 6.00b2 (6.00.e154320.x64).

Motherboard ASUS ROG Maximum Z690 Hero.

DIMMs are Corsair Vengeance DDR5 64 GB (2x32GB) 5200MHz.

NOTE: The DDR5-4000 shown on the screen is fine -- that's the motherboard's default clock for the memory and what the BIOS is currently configured for.

**Comment by debrouxl** [comment] 2022-06-27 06:33
Thanks for the report.
Besides 2 GB being reported for 32 GB sticks, a manufacturing year of 2002 is also incorrect for DDR5 memory - but that may well be what the RAM's SPD data contains.
Do any of the other hardware information reporting tools (CPU-Z, SIV, HWiNFO, Linux decode-dimms, etc.) report the same information ?

**Comment by rocketraman** [comment] 2022-06-27 06:45
> Do any of the other hardware information reporting tools (CPU-Z, SIV, HWiNFO, Linux decode-dimms, etc.) report the same information ?

I'll give decode-dimms a shot once the current memory test pass is complete!

**Comment by x86fr** [comment] 2022-06-27 09:17
Hi @rocketraman 

This is a known issue currently being investigated by the Asus BIOS Team. 
It only happen with the most recent 600-series BIOS from Asus.

**Comment by x86fr** [comment] 2022-07-02 13:03
yes it is. I'm still waiting for a feedback from Asus, but they're not sure if this is intentional or not at this point...

**Comment by rocketraman** [comment] 2022-07-04 12:25
For reference, `decode-dimms` doesn't return any information, but `dmidecode` lists the size of each stick correctly as 32GB. Output of one stick:

```
Handle 0x004B, DMI type 17, 92 bytes
Memory Device
        Array Handle: 0x004A
        Error Information Handle: Not Provided
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 32 GB
        Form Factor: DIMM
        Set: None
        Locator: Controller0-DIMM0
        Bank Locator: BANK 0
        Type: <OUT OF SPEC>
        Type Detail: Synchronous
        Speed: 4000 MT/s
        Manufacturer: Corsair
        Serial Number: 00000000
        Asset Tag: 9876543210
        Part Number: CMK64GX5M2B5200C40  
        Rank: 2
        Configured Memory Speed: 4000 MT/s
        Minimum Voltage: 1.1 V
        Maximum Voltage: 1.25 V
        Configured Voltage: 1.1 V
        Memory Technology: DRAM
        Memory Operating Mode Capability: Volatile memory
        Firmware Version: Not Specified
        Module Manufacturer ID: Bank 3, Hex 0x9E
        Module Product ID: Unknown
        Memory Subsystem Controller Manufacturer ID: Unknown
        Memory Subsystem Controller Product ID: Unknown
        Non-Volatile Size: None
        Volatile Size: 32 GB
        Cache Size: None
        Logical Size: None
```

**Comment by x86fr** [comment] 2022-08-15 16:23
Still working on it...

**Comment by mattzink** [comment] 2022-10-24 22:42
Just adding that I am also seeing this on my Asus z690 board (Bios 2107), and not only is the name and size wrong, but so is the speed and timings. The BIOS, Windows Task Manager, hwinfo, and cpu-z report all RAM information correctly.

Expected:
G.Skill Trident Z5 RGB 32 GB (2 x 16 GB) DDR5-6000 CL36-36-36-76 1.30V (f5-6000u3636e16gx2-tz5rk)

Actual:
![20221024_162840](https://user-images.githubusercontent.com/2976921/197643472-05123b22-e41b-43d8-8bec-0a5bc1c6ee18.jpg)

**Comment by rutsky** [comment] 2023-05-01 10:36
I'm on ASUS z690 Formula with BIOS 2305 and memtest86+ 6.10 from Ubuntu 23.04 and can not reproduce this issue.

Perhaps this was fixed in memtest86+ 6.10, since the two reports above are for 6.00?

![image](https://user-images.githubusercontent.com/46573/235441326-731ae52c-d13d-4824-b831-32b83a22dac5.png)

![image](https://user-images.githubusercontent.com/46573/235441462-86d0d1e2-aae8-457d-8fbb-ee9f964db6c1.png)

**Comment by rutsky** [comment] 2023-05-01 19:34
After some thinking I realised that this issue may be caused by enabled SPD write protection on some of the ASUS motherboards by default (at least it is the case on ASUS Z690 Formula).

The relevant setting in BIOS is in "Extreme Tweaker" -> "Tweaker's Paradise" -> "SPD Write Disable" - it needs to be set to `FALSE` to make reading of SPD work - this is the workaround for this issue:

![image](https://user-images.githubusercontent.com/46573/235514091-5911cb69-64a3-442a-b119-5e3c5410bb83.png)

I by setting "SPD Write Disable" = `TRUE` I can reproduce this issue:

![image](https://user-images.githubusercontent.com/46573/235514735-19ab9d76-9548-4ffb-8836-7f06bff681e6.png)

while expected:

![image](https://user-images.githubusercontent.com/46573/235515016-5c9dc3bf-9b38-4dc8-939c-b9e66bc7b1b0.png)

On DDR5 some of the information about memory model, XMP profiles, etc are stored in SPD at offsets that require page switching (e.g. fabrication year/week [are at offsets 515/516](https://github.com/memtest86plus/memtest86plus/blob/1f1fe5bfe871600dad3bd9a0de538d8e051353a9/system/smbus.c#L396-L397), while a single page size is [128 bytes](https://github.com/memtest86plus/memtest86plus/blob/1f1fe5bfe871600dad3bd9a0de538d8e051353a9/system/smbus.c#L1535)). Page switching requires [writes](https://github.com/memtest86plus/memtest86plus/blob/1f1fe5bfe871600dad3bd9a0de538d8e051353a9/system/smbus.c#L1537-L1541) into `SPD5_MR11` register and current Memtest86+ code is not handling write errors there, thus continues to read information from the wrong location --- this is the Memtest86+ bug that needs to be addressed.

Not sure if the write protection can be worked around, at least Memtest86+ should detect that the page switch failed and not display incorrect information.

For comparison, PassMark MemTest86 still displays some information, either obtained from the first page or by other means, output when SPD writes are disabled:

![image](https://user-images.githubusercontent.com/46573/235516495-cf0da7a6-0a85-4251-aff0-67640b7b930a.png)

PassMark MemTest86 output when SPD writes are enabled:

![image](https://user-images.githubusercontent.com/46573/235516750-cf8367f0-1eae-4406-80a8-ef74e0dff7e2.png)

**Comment by mattzink** [comment] 2023-05-01 20:00
There must be another means of getting that information, since as I said Windows Task Manager, hwinfo, and cpu-z report all RAM information/timings correctly.

**Comment by x86fr** [comment] 2023-05-01 20:16
Yes, this is an ASUS BIOS bug. They're aware of it since 6 months now. 

Basically, they must filter write commands and allow the bank switch write command to pass in all cases (while blocking bytes writes if SPD Write Disable is enabled). MSI do that correctly, but not ASUS on some BIOS (not all motherboards are impacted, 700-series MB are usually immune). According to their BIOS Team, this should be fixed on their latest BIOS (or about to be). 

If they don't solve it quickly, I will handle this and remove the wrong information with a quirk. I can also disable the write protection on our side (like Windows do natively), but I already FUBAR'd some DDR5 sticks while messing with writes, so better write a bit to see if they really solve this or not.

**Comment by mattzink** [comment] 2023-05-01 20:18
> Yes, this is an ASUS BIOS bug. They're aware of it since 6 months now.

Strange then it doesn't seem to affect other software besides memtest86+

**Comment by x86fr** [comment] 2023-05-01 21:34
> Strange then it doesn't stop other software from displaying this information

Not really : all Windows software benefits from the underlying Windows driver that deal with it. That's probably why they are in no rush to solve the issue natively.

**Comment by rutsky** [comment] 2023-05-01 22:13
Thanks for the information, Sam! Wasn't aware that SPD write "protection" supposed to still allow writes for page switching, it's good to hear that they are aware of this and supposedly working on the fix.

Reproduction [above](https://github.com/memtest86plus/memtest86plus/issues/110#issuecomment-1530115472) is for ASUS Z690 Formula with the BIOS version `2305` which was published 2023-03-22 and should be the latest public version (although it's no longer available on the official website).

**Comment by laozhoubuluo** [comment] 2024-01-02 16:02
Seems Memtest86+ v6.2.0 also have this issue.

The system configuration is:
CPU: Single Intel Core i7-14700K
Motherboard: ASUS TUF GAMING Z790-PLUS WIFI
Memory: Glowway DDR5 6400MHz 32G*2
BIOS Version: 1603 2023/12/13

![IMG_20240102_222919](https://github.com/memtest86plus/memtest86plus/assets/31075951/9b43a353-db89-4f97-ba9c-0c32774c5872)
![IMG_20240103_000059](https://github.com/memtest86plus/memtest86plus/assets/31075951/85433b19-8410-483d-977b-e04cdaa88c44)

**Comment by x86fr** [comment] 2024-01-02 16:11
Can you please check if you find a "SPD Write Protection" option on your BIOS setup and try to flip it?

**Comment by laozhoubuluo** [comment] 2024-01-02 17:19
> Can you please check if you find a "SPD Write Protection" option on your BIOS setup and try to flip it?

Display changed as screenshots, but some info also not reflect the truth like

**Comment by x86fr** [comment] 2024-01-02 18:36
If you're running Windows, can you please launch the latest CPU-Z and submit a validation for your computer?  I will check what's wrong. Also, v7.00 will be released in a couple day. You can try it using the nightly build from memtest.org.

**Comment by laozhoubuluo** [comment] 2024-01-03 03:23
> If you're running Windows, can you please launch the latest CPU-Z and submit a validation for your computer? I will check what's wrong. Also, v7.00 will be released in a couple day. You can try it using the nightly build from memtest.org.

1. https://valid.x86.fr/el9cfa
2. According to the motherboard manual, I should not turn off "SPD Write Protection". If confirm that nightly build will not write SPD incorrectly or cause other damage, I can try it.

**Closed** 2024-09-30 11:38 UTC
Labels: bug
