### ISSUE TITLE
Various issues on DL360 G7

### ISSUE THREAD

**Issue by teicors** [memtest86plus/memtest86plus#36] opened 2022-04-06 06:52 UTC
Hi,
while testing the ram of a HP DL360 G7 server with 60GB of ram and 2 processor, I got the error in the title and after few seconds the same error but on line 92.
The test was the #3 and I'm attaching a photo of the error below
![20220405_182858_1](https://user-images.githubusercontent.com/16402241/161912427-b1d489b9-df49-4caa-b7de-de21fec38074.jpg)

I cannot assign the problem or a bad bank of ram or a motherbard problem: the first test of the iso image was without any error. 
Can you give a suggestion?

**Comment by debrouxl** [comment] 2022-04-06 07:12
Does the internal error occur even in failsafe mode ?
AFAICS, the DL360 G7 has 18 RAM slots; it happens that memtest86+ 5.31b and older versions contain a bug which can trigger improper behaviour, including crashes and reboots, on computers with more than 16 RAM slots.
That bug is fixed in pcmemtest-derived memtest86+ 6.00.

**Comment by teicors** [comment] 2022-04-06 12:37
It's seems better ... :)

Thanks!

![20220406_143129_1](https://user-images.githubusercontent.com/16402241/161975934-7fe03239-d70c-441e-bd5a-3ad09d38e15f.jpg)

**Comment by debrouxl** [comment] 2022-04-06 14:54
This screenshot shows that the caches and RAM were not benchmarked, the board model was not printed, and only half of the hyperthreads supported by your computer were used. SMT disabled mode isn't supported yet by memtest86+, AFAICT - #9 .

Which build / Git commit ID did you use ? Did you pass `nosm nobench` arguments onto the command line ?

**Comment by teicors** [comment] 2022-04-06 15:46
I cloned locally the github repository, I used the README to build the executable and the "make iso" to generate the iso image. The I reboot the server and after the lunch I checked the soft running :)
I wait until the end for the test session and I'll give a look when the server restarts..
```
more .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/memtest86plus/memtest86plus.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
```
.. and I cannot choose any option using my usb keyboard... the memtest seems irresponsive to any key pressed: where insert the oiptions `nosm nobench` into the Makefile ?

**Comment by x86fr** [comment] 2022-04-06 16:46
SMT is probably disabled within BIOS (very common on DL360 G7) or only one CPU populated, and DMI seems empty (as shown on Memtest86+ 5.31b screenshot). SPD is not read because DDR3 Registered is not supported yet. Not sure about why the bench is not shown, but probably a strange memory map.

**Comment by teicors** [comment] 2022-04-06 17:03
I'll check into the BIOS about SMT, but looking about the CPU the latest version recognize ONLY one cpu.. in the version 5.31 you can see 24cores, but only 12 in 6.00.
And about the keyboard: in the 5.31 version I can useit, b ut in 6.00 no answer (even the leds are'nt working).
Obviously, same hardware regarding both tests.

**Comment by x86fr** [comment] 2022-04-06 17:15
Correct, there is an issue somewhere with the SMP table parsing on 6.00pre. 
About the keyboard, can you try to put `pause_at_start = true` in `config.c` and compile again?

The issue is you will not be able to pass the usb scanning screen because it waits indefinitly for a keypress (that's why I disabled it - WIP) but a screenshot of the screen would be nice.

PS: a fallback to legacy if no USB keyboards are detected is planned soon.

**Comment by teicors** [comment] 2022-04-06 17:27
Here's the start!
[Uploading t2{a198e66} (1d10cdf9-565f-4fc9-bd6c-6f6473f16a0c id=0x7f0a03a0) …]()

**Comment by x86fr** [comment] 2022-04-06 17:38
Unfortunately, UHCI controllers are not supported yet. 
You should try to plug your keyboard to the EHCI USB port if available externally  or pass `keyboard=legacy` as a kernel parameter

**Comment by teicors** [comment] 2022-04-06 17:46
how and where put `keyboard=legacy` ? Normally I'm putting it in the grub.cfg, but in this case I don't know ho and where put it :(

**Comment by martinwhitaker** [comment] 2022-04-06 18:21
At the end of the Build and Installation section of the README, there are some notes on how to build a test ISO that uses GRUB as an intermediate bootloader. With that, you can edit the boot command line on the fly in GRUB, or edit the configuration files in the grub directory to make permanent changes.

**Comment by martinwhitaker** [comment] 2022-04-06 19:53
I've pushed a fix for the "Failed to map device into virtual memory" message. It should now report "This controller type is not supported yet".

**Comment by teicors** [comment] 2022-04-07 06:10
Here's the requested files.
[acpidump.txt](https://github.com/memtest86plus/memtest86plus/files/8440028/acpidump.txt)
[dmidecode.txt](https://github.com/memtest86plus/memtest86plus/files/8440029/dmidecode.txt)
[DMI.data.uuencoded.txt](https://github.com/memtest86plus/memtest86plus/files/8440043/DMI.data.uuencoded.txt)

Hope this helps !

**Comment by debrouxl** [comment] 2022-04-08 13:02
Thanks, it does indeed help :)
1) dmidecode.txt shows that there's no DMI data struct type 2 (Base Board Information) in that computer's DMI data... and HP did it right: the availability of a type 2 struct instance is not mandated in the SMBIOS specification :)
Type 1 (System Information) is the mandatory type, even as early as SMBIOS 2.3 - so that's what memtest86+ ought to parse, at a priority higher than type 2, or even instead of type 2. I'll handle that.
2) I'll look at acpidump.txt later, but someone else can beat me to it ;)

**Comment by debrouxl** [comment] 2022-04-08 13:25
Alright, so I'll use type 1 as fallback.

**Comment by debrouxl** [comment] 2022-04-09 10:13
On the new "smbios_struct_type_1_support" branch, I have pushed a commit which does the type 2 -> type 1 fallback, as discussed yesterday. It builds, but I haven't yet tested it on my side for absence of regression.
@teicors : could you build that, and test whether "HP ProLiant DL360 G7" (possibly with a  now appears on the bottom of your screen ? TIA :)

According to `dmidecode`, one of my computers exposes... *interesting*... DMI data:
```
Handle 0x0001, DMI type 1, 25 bytes
System Information
        Manufacturer: ... .u.......w.....#...N...\   
        Product Name: .#...t.....                    
        Version: . ...a.`W..F...+.Q..Y_.
        Serial Number: w.W......FQ..Y_..g...F..a.....m
        UUID: 69faac50-58ce-11d4-a03d-080009e4c98a
        Wake-up Type: Power Switch

Handle 0x0002, DMI type 2, 8 bytes
Base Board Information
        Manufacturer: .....b`............t0.>..mt%...
        Product Name: .......K.....8.t...g.u... .#. -
        Version: ...#..$.$.<....        
        Serial Number: b. <.u..W..<.u..w.....s....s...

Handle 0x0003, DMI type 3, 17 bytes
Chassis Information
        Manufacturer: ........t.......$.tM..t...t..>.
        Type: <OUT OF SPEC>
        Lock: Not Present
        Version: u..Y.>..mui.P.>..mt3...
        Serial Number: ..@t....y.tP....@u.......2....3
        Asset Tag: .........>..mu-...:...u....:...
        Boot-up State: Unknown
        Power Supply State: Unknown
        Thermal State: Unknown
        Security Status: Unknown
        OEM Information: 0x00000000
```

**Comment by teicors** [comment] 2022-04-09 17:51
Hi,
here's the screen from the latest branch 
![immagine_2022-04-09_194643146](https://user-images.githubusercontent.com/16402241/162585525-73963765-5f34-490b-96e3-6c5af28b4412.png)

I can see the model of server, but I cannot figure out the meaning of the amount of ram: the server comes with 60GB of ram, but why I can see two checks? The first ends at 59.9GB and the second starts from 60 and ends at 60.4GB: is it normal ?

![immagine_2022-04-09_195034854](https://user-images.githubusercontent.com/16402241/162585672-82468b79-8848-4fdf-9980-45c984a1b6ed.png)

**Comment by debrouxl** [comment] 2022-04-09 18:53
Good, the fallback to type 1 works :)
And all 24 hardware threads are now somehow detected.

As for 60.4 GB vs. 60 GB: AFAIK, it's due to the hole in the memory layout of all of the x86(_64) computers equipped with 4+ GB of RAM that I know about. All of the computers on which I've tested memtest86+ / pcmemtest do that. The size of the hole in the memory layout depends on the memory areas declared by the BIOS and passed to the bootloader & OS through e.g. E820.
For instance, one of my MBs has 2.5 GB of RAM below 4 GB and 1.5 or 5.5 GB of RAM above 4 GB, depending on whether I populate a single or both DDR3 RAM slots with 4 GB sticks.

**Comment by teicors** [comment] 2022-04-10 07:32
And now I wait to use the keyboard :)

**Comment by martinwhitaker** [comment] 2022-04-11 21:08
I've now added support for UHCI controllers. Please test if it works for you.

**Comment by teicors** [comment] 2022-04-19 08:04
since last Monday, I can't do any further test in order an hw issue: I'm waiting the replacement part (I hope at the beginning of next week)...

**Comment by mmuman** [comment] 2022-04-23 16:25
FWIW our fablab got donated a ML350 G6 and I'm currently testing 2a7631d on. Currently with a PS/2 keyboard though, but I can try USB too.

**Comment by teicors** [comment] 2022-04-24 07:22
Next Tuesday i'll do some test with the DL360 with the branch smbios_struct_type_1_support to check the support for usb keyboard.

**Comment by debrouxl** [comment] 2022-04-24 07:34
You should use the main branch instead, as smbios_struct_type_1_support was merged there :)

**Comment by mmuman** [comment] 2022-04-24 22:25
> FWIW our fablab got donated a ML350 G6 and I'm currently testing [2a7631d](https://github.com/memtest86plus/memtest86plus/commit/2a7631daab811fc8ca12c2eb5f0dcc974fe2fc8b) on. Currently with a PS/2 keyboard though, but I can try USB too.

For the record, it went fine, unlike version 5 which froze as it did on may other machines for me. I also tried with a USB keyboard.

**Comment by teicors** [comment] 2022-04-26 09:26
It works fine for me. Great !

![20220426_110654_1](https://user-images.githubusercontent.com/16402241/165268567-35a1fad4-cb46-48ff-ba9f-f4cfa4470568.jpg)


![20220426_110759_1](https://user-images.githubusercontent.com/16402241/165268521-69cdec83-2f49-49c5-8553-facf5ddad893.jpg)

**Closed** 2022-04-26 09:30 UTC
