### ISSUE TITLE
unable to run memtest.efi system from grub on hard disk or via PXE

### ISSUE THREAD

**Issue by ajschorr** [memtest86plus/memtest86plus#63] opened 2022-05-10 01:17 UTC
On a Tyan B8036G68V4E4HR-LE server with an AMD EPYC 7443P cpu, I am able to run memtest from
the bootable memtest.iso. But when I try to run memtest.efi from grub, either directly from hard disk or
via UEFI PXE, it looks promising at first: the screen turns blue, and I see "Status: Init." at the upper
right, but then the system resets. Is there any way to troubleshoot what's going wrong?

Thanks,
Andy

**Comment by ajschorr** [comment] 2022-05-10 16:49
When you say "initial option menu", are you talking about <F1> Configuration? The system crashes before
I can do anything. I have screen capture videos, if that might be helpful.

With "nobench" and "trace", it prints a bunch of stuff and then seems to hang:

CPU Trace
---  ------------
0  program size 218kB
0  low_load_addr  0000000001000
0  high_load_addr 0000003ff93000
0  pm  00000000000000 - 000000000009a
...

I did not count the leading zeros in those values, but that gives you a rough idea. It then just sits there doing nothing
until I power-cycle it.

**Comment by ajschorr** [comment] 2022-05-10 16:53
Here's a screenshot of the screen I get when running with these args: 
   trace nobench console=ttyS0,4
![Screenshot from memtest nobench trace avi](https://user-images.githubusercontent.com/12937824/167681847-f7c823ee-2350-4490-8003-c024e6e9071d.png)

**Comment by ajschorr** [comment] 2022-05-10 19:08
Ah, OK. I hit "Enter" once, and it added another "0 pm ..." line at the bottom of the screen. Then
I hit Enter again and it rebooted. Does that help?

**Comment by ajschorr** [comment] 2022-05-10 19:09
Here is the screenshot after hitting Enter once. The next Enter causes a reboot.
![Screenshot from video_10-5-2022_15-5-7_part1 avi](https://user-images.githubusercontent.com/12937824/167704105-a8f2ec30-9b62-4383-b046-cb41f247bde4.png)

**Comment by x86fr** [comment] 2022-05-10 20:24
Can you try with SMP disabled?

**Comment by martinwhitaker** [comment] 2022-05-10 23:28
Your version of GRUB appears to be loading the program at an unusual address (3ff93000). I don't think it should, as the setup header doesn't have the relocatable flag set, but it should work anyway. Forcing my version of GRUB to load at that address does reproduce the bug.

**Comment by 01e3** [comment] 2022-05-11 02:52
Have the same problem - instant reboot on a HP z440, I can even reproduce this from the official "Linux ISO w/ GRUB (64 bits)" image when booted with via "Start Memtest86+ using 'linuxefi' command", where "linux seems to work well.

I will capture the trace with trace nobench to be sure.

**Comment by debrouxl** [comment] 2022-05-11 06:57
3FF93000 is quite close to 40000000. Are some stack pointers and BSS getting spilled over 40000000 ?
Adding 218*1024 (from the earlier screenshot showing the program size) yields 3FFC9800; when I build memtest86+, the terminal output contains
`ld --defsym=_bss_size=292640 -T ldscripts/memtest_efi.lds boot/header.o boot/setup.o -b binary memtest_shared.bin -o memtest.efi`
and adding that to 3FFC9800 yields 40010F20.

I'll check the high_load_addr on my PowerEdge R815, on which memtest86+ still reboots spontaneously to date - I did not carry the issue over to this repo yet; amusingly, I was trying to make progress on the debug work yesterday evening. So far, I've seen that it reboots when starting (some) APs.

**Comment by ajschorr** [comment] 2022-05-11 14:16
I  pulled the latest version from git. It now works with "nosmp", but continues to crash without it.

Also, FYI, I'm getting no output on the serial console, despite invoking it with args: nosmp console=ttyS0,115200

**Comment by ajschorr** [comment] 2022-05-11 14:18
In case it matters, I'm using grub2-efi-x64-2.02-106.el8.0.2.x86_64 on a Rocky Linux 8.5 system.

**Comment by x86fr** [comment] 2022-05-11 14:46
> I pulled the latest version from git. It now works with "nosmp", but continues to crash without it.
> 
> Also, FYI, I'm getting no output on the serial console, despite invoking it with args: nosmp console=ttyS0,115200

Try inverting the options (console=ttyS0,115200 nosmp)

**Comment by ajschorr** [comment] 2022-05-13 12:54
So this works with nosmp, but it's really slow. Is there any way to get this fixed so that it can run in SMP mode?

**Comment by debrouxl** [comment] 2022-05-13 19:58
On my PowerEdge R815, in `trace` mode:
* setting SEQUENTIAL_AP_START in `system/smp.c` does not help, the computer reboots in `smp_start(cpu_state);`;
* `nosmp` helps a bit: the execution goes further, all the way through the try runs (two passes from 0 to 10), but when the test starts for real (the upper right part of the screen starts becoming alive), the computer reboots after the next press on Enter.

**Comment by martinwhitaker** [comment] 2022-05-14 07:52
> So this works with nosmp, but it's really slow. Is there any way to get this fixed so that it can run in SMP mode?

Please be patient - I don't have much spare time at the moment. If you need a quick fix, you need a more up-to-date version of GRUB where the bug in the linuxefi command has been fixed (or an older version that doesn't alias the linux command to linuxefi). Or use rEFInd instead of GRUB.

**Comment by ajschorr** [comment] 2022-05-14 15:43
No worries. I'm going to stick with the stock GRUB provided by the O/S. There's no rush. I'm trying the PassMark version to double-check my new system. They claim to report on EDAC ECC errors corrected; does this memtest86+ handle that? I don't see any sign of it in the code, but I haven't looked closely.

**Comment by debrouxl** [comment] 2022-05-14 17:01
Nope, you're correct, EDAC reporting is not supported by this version of the open-source memtest86+ :)
According to the changelog, it was removed in 2011 for reliability, complexity and maintenance burden reasons. Adding reliable, tested support for every new EDAC controller model, and testing for regressions, is something a company selling expensive proprietary software can pay people to work on, but it's hard to achieve in a volunteer pure FLOSS project. PassMark will have to do something after the upcoming release of memtest86+ 6.00 ^^

**Comment by x86fr** [comment] 2022-05-14 17:19
Or maybe it was removed in 2011 because they never wanted to share effort on open-source software (because it was re-added quickly in their closed-source build). Anyway, support for ECC/EDAC is planned on Memtest86+ in the future. Technically, adding it is not very complex as soon as we will have the code to access SoC MMIO Registers (which is planned soon to get actual RAM timings information).

**Comment by 01e3** [comment] 2022-05-14 17:21
Given that it seems like a popular request, should we create a dedicated bug to track adding ECC/EDAC?

**Comment by x86fr** [comment] 2022-05-14 17:58
Actually, you're the first to ask. Better wait a bit to avoid flooding with features request that will only be added in a distant future.

**Comment by martinwhitaker** [comment] 2022-05-14 22:44
Please test if this patch fixes it for you:
````
--- a/boot/startup64.S
+++ b/boot/startup64.S
@@ -556,7 +556,7 @@ ap_trampoline:
        movl    %ebx, %eax
        addl    $(gdt - startup), %eax
        movl    %eax, (ap_gdt_descr - ap_trampoline + 2)
-       lgdt    ap_gdt_descr - ap_trampoline
+data32 lgdt    ap_gdt_descr - ap_trampoline
 
        # Set the page directory base address.
 
````

**Comment by debrouxl** [comment] 2022-05-14 22:49
Wow. I was looking at the 64-bit startup code, and this line caught my eye (it's not rip-relative or label argument, it's a difference of labels), so I was trying to find other examples of `lgdt` usage, before raising the matter :)
I should be able to try that "tomorrow" morning, after sleep that is.

**Comment by ajschorr** [comment] 2022-05-15 00:26
Thanks. That patch seems to fix the problem.

**Comment by debrouxl** [comment] 2022-05-15 09:41
Likewise for me on the PowerEdge R815 in 64-bit UEFI mode. Good job :)
So it means that the linear address ended up being wrong when the program loaded at a sufficiently high memory address ?

**Comment by martinwhitaker** [comment] 2022-05-15 11:11
> So it means that the linear address ended up being wrong when the program loaded at a sufficiently high memory address ?

No, the AP is running in real mode at that point, so that section of code starts with a .code16 directive to tell the assembler to generate 16-bit instructions by default. The 16-bit variant of lgdt only loads the first three bytes of the base address from the GDT descriptor, so we have to force the assembler to use the 32-bit variant of lgdt.

**Comment by 01e3** [comment] 2022-05-15 16:39
Here is a similar fix in ipxe for a reference: https://git.socialnerds.org/david/ipxe/commit/29e6f9835ea0277c262b1ab2c4acee1d69cb7099

**Comment by martinwhitaker** [comment] 2022-05-15 17:26
The fix has been pushed to the main branch, so closing.

**Closed by martinwhitaker** 2022-05-15 17:26 UTC

**Comment by 01e3** [comment] 2022-05-15 19:25
I also confirm that this fixed the reboot problem on HP z440 in UEFI. Thanks!

**Comment by jusw** [comment] 2022-05-28 20:06
> Actually, you're the first to ask. Better wait a bit to avoid flooding with features request that will only be added in a distant future.

I second that request for a dedicated tracker for adding ECC capability, please. I'm pretty surprised it isn't supported TBH - especially since googling seems to suggest that at least some people think it does! I am new to the whole ECC world though and everything about it seems surprising, not least its lack of wider adoption.

**Comment by 01e3** [comment] 2022-06-01 04:26
Ha... good timing...

I just upgraded memory on one of my workstations and it passed 24h+ test with no issues reported. However, it takes less than 1m for prime95 to cause the Linux kernel to spam dmesg with:

```
[  373.606540] mce: [Hardware Error]: CPU 0: Machine Check: 0 Bank 12: c8000e0e00800093
[  373.607143] mce: [Hardware Error]: TSC 0 MISC c908468044445c00
[  373.607726] mce: [Hardware Error]: PROCESSOR 0:306e4 TIME 1653728202 SOCKET 0 APIC 2 microcode 42e
```

which decodes to:

```
Hardware event. This is not a software error.
CPU 0 BANK 12
MISC c908468044445c00
TIME 1653728202 Sat May 28 01:56:42 2022
MCG status:
MCi status:
Error overflow
Corrected error
MCi_MISC register valid
MCA: MEMORY CONTROLLER RD_CHANNEL3_ERR
Transaction: Memory read error
MemCtrl: Corrected memory read error

STATUS c8000e0e00800093 MCGSTATUS 0
CPUID Vendor Intel Family 6 Model 62 Step 4
SOCKET 0 APIC 2 microcode 42e

```

Same for Windows (via Microsoft-Windows-WHEA-Logger).

It turns out one of 4 "new" RDIMMS was bad. 

Filed https://github.com/memtest86plus/memtest86plus/issues/91 for the ECC support. :) Not expecting this will make it ready faster, but it would be good to have a place to track it.

**Comment by x86fr** [comment] 2022-06-01 11:53
Can you try to save that defective memory stick? It's an invaluable tool for debugging and I only have access to "consumer" (unregistered/unbuffered) DIMMs from the RMA teams.

**Comment by 01e3** [comment] 2022-07-29 07:45
Forgot to mention - yes, I kept the defective memory stick. It will wait until we have some code ready to test.
